

import edu.rit.ds.RemoteEvent;

/**
 * Remote event which will be generated by the GPSOffice objects. Customer and
 * headquarters will listen this type of events.
 * 
 * @author Shridhar Bhalekar
 *
 */
public class PacketEvent extends RemoteEvent{

	private static final long serialVersionUID = 1L;
	
	/**
	 * Message intended for the customer and headquarters
	 */
	private String message;
	
	/**
	 * Tracking number of the packet for which event is generated
	 */
	private long trackNumber;
	
	/**
	 * Creates a PacketEvent object
	 * 
	 * @param message message intended for the listeners
	 * @param trackNumber packet tracing number
	 */
	public PacketEvent(String message, long trackNumber) {
		this.message = message;
		this.trackNumber = trackNumber;
	}
	
	/**
	 * Getter which returns the tracking number of Packet
	 * @return
	 */
	public long getTrackNumber() {
		return this.trackNumber;
	}
	
	/**
	 * Getter which returns the message
	 * @return message for listeners
	 */
	public String getMessage() {
		return this.message;
	}
}
